Modules:
# - module: 0
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/640M_Ldis.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/640M_Ldis.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 2
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/640M_Ldis.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/640M_Ldis.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 4
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/640M_Ldis.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/640M_Ldis.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 6
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/640M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/640M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 8
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 9
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 9
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 10
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 11
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 12
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
- module: 13
  chips:
  - chip: 0
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
  - chip: 1
    startfile: "config/altiroc/startup_periphery/320M_Len.txt"
    vth_thre: 0
    vthcfile: "config/altiroc/Vthc/empty.txt"
