Lpgbts:
- lpgbt: 0
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 10
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM01
    Vessel: D
    name: FBM-FR-028
  - module: 2
    F_or_B: F
    Layer: 0
    Mod_Assembly: 9
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 8
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 6
    F_or_B: F
    Layer: 0
    Mod_Assembly: 7
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 6
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 9
    F_or_B: F
    Layer: 0
    Mod_Assembly: 5
    Mod_in_Row_in_DU_AS: 5
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FO01
    Vessel: D
    name: IFAE_104
  - module: 10
    F_or_B: F
    Layer: 0
    Mod_Assembly: 4
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FO01
    Vessel: D
    name: IFAE_102
  - module: 11
    F_or_B: F
    Layer: 0
    Mod_Assembly: 3
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FO01
    Vessel: D
    name: IJCLab_001
  - module: 12
    F_or_B: F
    Layer: 0
    Mod_Assembly: 2
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FO01
    Vessel: D
    name: IFAE_101
  - module: 13
    F_or_B: F
    Layer: 0
    Mod_Assembly: 1
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FO01
    Vessel: D
    name: FM006
- lpgbt: 1
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 10
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM01
    Vessel: D
    name: FBM-FR_022
  - module: 2
    F_or_B: F
    Layer: 0
    Mod_Assembly: 9
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 8
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 6
    F_or_B: F
    Layer: 0
    Mod_Assembly: 7
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 6
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 9
    F_or_B: F
    Layer: 0
    Mod_Assembly: 5
    Mod_in_Row_in_DU_AS: 5
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FO01
    Vessel: D
    name: FM005
  - module: 10
    F_or_B: F
    Layer: 0
    Mod_Assembly: 4
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FO01
    Vessel: D
    name: FM018
  - module: 11
    F_or_B: F
    Layer: 0
    Mod_Assembly: 3
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FO01
    Vessel: D
    name: FM017
  - module: 12
    F_or_B: F
    Layer: 0
    Mod_Assembly: 2
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FO01
    Vessel: D
    name: FM016
  - module: 13
    F_or_B: F
    Layer: 0
    Mod_Assembly: 1
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FO01
    Vessel: D
    name: IJCLab_003
- lpgbt: 2
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 10
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM01
    Vessel: D
    name: FBM-FR-027
  - module: 2
    F_or_B: F
    Layer: 0
    Mod_Assembly: 9
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 8
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 6
    F_or_B: F
    Layer: 0
    Mod_Assembly: 7
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 6
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM02
    Vessel: D
    name: .nan
  - module: 9
    F_or_B: F
    Layer: 0
    Mod_Assembly: 5
    Mod_in_Row_in_DU_AS: 5
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FO01
    Vessel: D
    name: IJCLab_002
  - module: 10
    F_or_B: F
    Layer: 0
    Mod_Assembly: 4
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FO01
    Vessel: D
    name: FM010
  - module: 11
    F_or_B: F
    Layer: 0
    Mod_Assembly: 3
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FO01
    Vessel: D
    name: FM001
  - module: 12
    F_or_B: F
    Layer: 0
    Mod_Assembly: 2
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FO01
    Vessel: D
    name: FM003
  - module: 13
    F_or_B: F
    Layer: 0
    Mod_Assembly: 1
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FO01
    Vessel: D
    name: FM004
- lpgbt: 3
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 16
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FI01
    Vessel: D
    name: M007
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 15
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FI01
    Vessel: D
    name: M008
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 13
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM01
    Vessel: D
    name: M015
  - module: 10
    F_or_B: F
    Layer: 0
    Mod_Assembly: 12
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM01
    Vessel: D
    name: M016
  - module: 12
    F_or_B: F
    Layer: 0
    Mod_Assembly: 11
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM01
    Vessel: D
    name: M021
- lpgbt: 4
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 15
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FI01
    Vessel: D
    name: FBM-FR_015
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 14
    Mod_in_Row_in_DU_AS: 5
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM01
    Vessel: D
    name: M012
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 13
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM01
    Vessel: D
    name: FBM-FR_025
  - module: 10
    F_or_B: F
    Layer: 0
    Mod_Assembly: 12
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM01
    Vessel: D
    name: FBM-FR_023
  - module: 12
    F_or_B: F
    Layer: 0
    Mod_Assembly: 11
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FM01
    Vessel: D
    name: FBM-FR_021
- lpgbt: 5
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 15
    Mod_in_Row_in_DU_AS: 1
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FI01
    Vessel: D
    name: M010
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 14
    Mod_in_Row_in_DU_AS: 5
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM01
    Vessel: D
    name: M011
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 13
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM01
    Vessel: D
    name: FBM-FR-012
  - module: 10
    F_or_B: F
    Layer: 0
    Mod_Assembly: 12
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM01
    Vessel: D
    name: M013
  - module: 12
    F_or_B: F
    Layer: 0
    Mod_Assembly: 11
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FM01
    Vessel: D
    name: M017
- lpgbt: 6
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 18
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FI01
    Vessel: D
    name: FBM-FR-017
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 17
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FI01
    Vessel: D
    name: M006
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 16
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FI01
    Vessel: D
    name: FBM-FR_008
  - module: 12
    F_or_B: F
    Layer: 0
    Mod_Assembly: 14
    Mod_in_Row_in_DU_AS: 5
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 1
    Row_in_DU_AS: 1
    SupportUnit_Type: FM01
    Vessel: D
    name: M020
- lpgbt: 7
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 18
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FI01
    Vessel: D
    name: M005
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 17
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 2
    Row_in_DU_AS: 2
    SupportUnit_Type: FI01
    Vessel: D
    name: FBM-FR_007
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 16
    Mod_in_Row_in_DU_AS: 2
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FI01
    Vessel: D
    name: FBM-FR-014
- lpgbt: 8
  Modules:
  - module: 0
    F_or_B: F
    Layer: 0
    Mod_Assembly: 18
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FI01
    Vessel: D
    name: .nan
  - module: 4
    F_or_B: F
    Layer: 0
    Mod_Assembly: 18
    Mod_in_Row_in_DU_AS: 4
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FI01
    Vessel: D
    name: FBM-FR-005
  - module: 8
    F_or_B: F
    Layer: 0
    Mod_Assembly: 17
    Mod_in_Row_in_DU_AS: 3
    PEB_Type: 1F
    Quadrant: 0
    Row_Assembly: 3
    Row_in_DU_AS: 3
    SupportUnit_Type: FI01
    Vessel: D
    name: FBM-FR-013
